import './globals.css'
import { NavBar } from './components/NavBar/NavBar'
import { Footer } from './components/Footer/Footer'

export const metadata = {
  title: 'Addi',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='es' className='px-8 font-customFont'>
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
